/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import model.Address;
import model.Person;
import model.PersonDirectory;
import ui.PersonManager.PersonMngWorkAreaJPanel;
import ui.PersonManager.ViewPersonJPanel;

/**
 *
 * @author vartika
 */
public class MainJFrame extends javax.swing.JFrame {
     
   
     private PersonDirectory personDirectory;


    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        this.personDirectory = new PersonDirectory();
        generateDemodata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnOpen = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(120);
        splitPane.setDividerSize(2);
        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(0, 153, 153));

        btnOpen.setFont(new java.awt.Font("Heiti SC", 0, 18)); // NOI18N
        btnOpen.setText("Open Person Manager");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1163, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        splitPane.setTopComponent(topJPanel);

        userProcessContainer.setBackground(new java.awt.Color(255, 255, 255));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1072, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        PersonMngWorkAreaJPanel panel = new PersonMngWorkAreaJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("PersonMngWorkAreaJPanel", panel);
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnOpenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void generateDemodata() {

    // Creating first Person object
    Person person1 = personDirectory.addPerson();
    person1.setFirstName("John");
    person1.setLastName("Doe");
    person1.setEmail("john.doe@example.com");
    person1.setAge(30);
    person1.setHeight(1.75); // height in meters
    person1.setSocialSecurityNumber(123456789L);
    person1.setGender('M');

    // Home and Work Address for person1
    Address homeAddress1 = new Address("123 Elm Street", "Apt 4B", "Los Angeles", "California", "90001", "3105551234");
    Address workAddress1 = new Address("456 Maple Avenue", "Suite 800", "Los Angeles", "California", "90002", "3105555678");
    person1.setHomeAddress(homeAddress1);
    person1.setWorkAddress(workAddress1);

    // Creating second Person object
    Person person2 = personDirectory.addPerson();
    person2.setFirstName("Jane");
    person2.setLastName("Smith");
    person2.setEmail("jane.smith@example.com");
    person2.setAge(28);
    person2.setHeight(1.65); // height in meters
    person2.setSocialSecurityNumber(987654321L);
    person2.setGender('F');

    // Home and Work Address for person2
    Address homeAddress2 = new Address("789 Pine Street", "House 2", "San Francisco", "California", "94110", "4155559876");
    Address workAddress2 = new Address("101 Oak Avenue", "Floor 2", "San Francisco", "California", "94111", "4155554321");
    person2.setHomeAddress(homeAddress2);
    person2.setWorkAddress(workAddress2);

    // Creating third Person object
    Person person3 = personDirectory.addPerson();
    person3.setFirstName("Michael");
    person3.setLastName("Johnson");
    person3.setEmail("michael.johnson@example.com");
    person3.setAge(40);
    person3.setHeight(1.80); // height in meters
    person3.setSocialSecurityNumber(555444333L);
    person3.setGender('M');

    // Home and Work Address for person3
    Address homeAddress3 = new Address("456 Cedar Street", "Apt 12C", "New York", "New York", "10001", "2125551234");
    Address workAddress3 = new Address("789 Birch Avenue", "Office 200", "New York", "New York", "10002", "2125555678");
    person3.setHomeAddress(homeAddress3);
    person3.setWorkAddress(workAddress3);

    // Creating fourth Person object
    Person person4 = personDirectory.addPerson();
    person4.setFirstName("Emily");
    person4.setLastName("Williams");
    person4.setEmail("emily.williams@example.com");
    person4.setAge(35);
    person4.setHeight(1.68); // height in meters
    person4.setSocialSecurityNumber(123987456L);
    person4.setGender('F');

    // Home and Work Address for person4
    Address homeAddress4 = new Address("321 Spruce Street", "Apt 8D", "Chicago", "Illinois", "60601", "3125559876");
    Address workAddress4 = new Address("123 Oak Boulevard", "Suite 500", "Chicago", "Illinois", "60602", "3125554321");
    person4.setHomeAddress(homeAddress4);
    person4.setWorkAddress(workAddress4);

    // Creating fifth Person object
    Person person5 = personDirectory.addPerson();
    person5.setFirstName("David");
    person5.setLastName("Brown");
    person5.setEmail("david.brown@example.com");
    person5.setAge(45);
    person5.setHeight(1.85); // height in meters
    person5.setSocialSecurityNumber(654789123L);
    person5.setGender('M');

    // Home and Work Address for person5
    Address homeAddress5 = new Address("789 Ash Street", "House 15", "Houston", "Texas", "77001", "7135554321");
    Address workAddress5 = new Address("987 Maple Boulevard", "Office 101", "Houston", "Texas", "77002", "7135555678");
    person5.setHomeAddress(homeAddress5);
    person5.setWorkAddress(workAddress5);
}

    }

